### ISSUE TITLE
Character controller 

### ISSUE THREAD

**Issue by fedesanches** [GauchoGSDMS/DeadManSteps#12]
Crear el movimiento del jugador + integración animaciones. 

Re hacer el sistema de la cámara donde: 

1) La cámara se puede mover libremente. (Como esta ahora)
2) Si el personaje se mueve para algún lado volver la cámara atrás del personaje y volver a seguirlo. 
3) El personaje solo podra correr con el boton Shift.

**Comment by ColoLP** [comment]
Se utilizaron 3 blend trees para poder animar correctamente al personaje. 

Quedo con la camara moviendose de manera orbital (Libremente) y a su vez, ahora se puede mover agachado y correr, modificando los niveles de velocidad.
